# PyTorch music classification

## Importing packages
### System and utility

In [4]:
import os
import random
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

### Importing PyTorch


In [5]:
import torch
from torch import optim
from torch import nn as nn

## Global constants
* CHUNK_SIZE defines the number of seconds to take from a song in order to train and classify
* BATCH_SIZE determines how many different pieces of music are seen by the machine learning algorithm at one point in time
* LEARNING_RATE is a parameter for the learning algorithm telling the algorithm "how fast or how much it is supposed to learn from a set of samples"
* ITERATIONS sets the number of overall chunks of music the neural network is going to see and learn from

In [6]:
CHUNK_SIZE = 20000
BATCH_SIZE = 512
LEARNING_RATE = 1e-3
ITERATIONS = 5000

### Check if machine is ready for GPU use
Note that using GPU yields heavy speed-ups as hardware is optimized for most machine learning operations

In [7]:
is_gpu = torch.cuda.is_available()
print("GPU detected: ", is_gpu)

('GPU detected: ', True)


## Data loader
Loading the data from a wav file and converting it into a numerical (float) form that is usable to a neural network. Here, the machine learning is going to be done on "raw" audio data. Alternatives could be "visual representations of soundwaves"

In [8]:
from scipy.io import wavfile

def random_wav_slice(path, slice_size, debug=False, category="bla", downsample=7):
    sample_rate, data = wavfile.read(path)
    data = data[::7]

    slice_start = random.randint(0, data.shape[0] - slice_size - 1)
    slice_end = slice_start + slice_size

    convert_16_bit = float(2**15)
    data = data[slice_start:slice_end]/(convert_16_bit+1.0)

    data = data.astype(np.float32)

    return data

def generate_categories(path):
    categories = dict.fromkeys(os.listdir(path))

    for c in categories:
        c_abspath = os.path.join(path, c)
        audio_files = filter(lambda n: n.endswith(".wav"), os.listdir(c_abspath))
        categories[c] = [os.path.join(c_abspath, au) for au in audio_files]

    return categories

def random_sample(categories, slice_size=20000, debug=False, batch_size=128):
    sample_tensors = []
    target_tensors = []

    for batch_i in xrange(batch_size):

        category = random.choice(list(categories.keys()))
        category_index = sorted(list(categories.keys())).index(category)

        random_file = random.choice(list(categories[category]))
        sample_data = random_wav_slice(random_file, slice_size, category=category)

        target_tensors.append(category_index)
        sample_tensors.append(sample_data)

    sample_tensors = torch.from_numpy(np.array(sample_tensors, dtype=np.float32))
    target_tensors = torch.from_numpy(np.array(target_tensors, dtype=np.int64))

    return target_tensors, sample_tensors

def print_predictions(output_tensor, categories):
    values, indexes = output_tensor.topk(3, 1, True)

    for i in range(3):
        value = values[0][i].data[0]
        index = indexes[0][i].data[0]
        name = sorted(list(categories.keys()))[index]
        print("{}: {} ({})".format(i, name, value))

    print(80*"#")
    print("\n\n")

### TODO: PLAY AUDIO SAMPLES HERE

## Defining the neural network
A very simple neural network with 3 overall hierarchical layers. From one layer to another all neurons are connected to all other neurons, usually referred to as "fully-connected" or "Multi-layer perceptron (MLP)". In the last layer there is as many output neurons as there is classes to distinguish in the task. This is motivated from the concept of "grandmother-cells" in Biology, where it is assumed that if you see your grandmother, one particular neuron is activated. In our example, that means that we have one neuron for "rock", one for "blues" etc. This is one of the simplest neural networks one can imagine as it doesn't have any complicated structure. 

In PyTorch neural networks are easily defined through the high-level AP. You decide on the amount of neurons ("hidden-size") in each layer and the connectivity pattern (linear = everything is connected). You then define a "forward" function in which the ordering of the layers is defined. PyTorch then takes care of optimization and updating of the network

In [3]:
class MLP(nn.Module):

    def __init__(self, chunk_size, num_classes, hid1_size=300, hid2_size=128):
        super(MLP, self).__init__()

        self.lin1 = nn.Linear(chunk_size, hid1_size)
        self.act1 = nn.ReLU(True)

        self.lin2 = nn.Linear(hid1_size, hid2_size)
        self.act2 = nn.ReLU(True)

        self.lin3 = nn.Linear(hid2_size, num_classes)

    def forward(self, x):
        x = self.act1(self.lin1(x))
        x = self.act2(self.lin2(x))
        x = self.lin3(x)
        return x

NameError: name 'nn' is not defined

## Initializing neural network model, data loader and definition of how to train the neural network

### data

In [7]:
categories = generate_categories("../../../datasets/gtzan")
CLASSES = categories.keys() # ["rock", "blues", ...]

### Initializing the neural network model
Constructing the network defined earlier for the first time. This network has not seen any data yet and produces completely random output as all concepts are new at this point in time. 

In [8]:
model = MLP(CHUNK_SIZE, len(CLASSES), 256, 128)
print(model)

MLP (
  (lin1): Linear (20000 -> 256)
  (act1): ReLU (inplace)
  (lin2): Linear (256 -> 128)
  (act2): ReLU (inplace)
  (lin3): Linear (128 -> 10)
)


### Select a loss function (to train the network) and an optimization algorithm
There is many optimization algorithms and loss functions. PyTorch has a catalogue of these and specifying these is only two lines of code. 

In [9]:
optimizer = optim.Adam(model.parameters(), LEARNING_RATE, weight_decay=1e-4)
loss_fn = nn.CrossEntropyLoss()

### Tell the neural network model and optimizer to use GPU acceleration if available.

In [10]:
if is_gpu:
    model = model.cuda()
    loss_fn = loss_fn.cuda()

### Set the neural network model into "training" mode, that is tell the neural network to learn from the data it is going to see. Create a list to store intermediate results, so that we can monitor how our neural network is getting better! 

In [11]:
model.train()

losses = []

## Train the neural network model

In [12]:
for i in xrange(ITERATIONS):

    # sample a mini-batch from the data
    target_tensor, sample_tensor = random_sample(categories, slice_size=CHUNK_SIZE, batch_size=BATCH_SIZE)

    # place it on GPU if a GPU is available
    if is_gpu:
        target_tensor = target_tensor.cuda()
        sample_tensor = sample_tensor.cuda()

    # put the data into a PyTorch Autograd Variable that is used for optimization
    input_var = torch.autograd.Variable(sample_tensor)
    target_var = torch.autograd.Variable(target_tensor)

    # do the actual calculation and learning
    optimizer.zero_grad()
    output = model(input_var)
    loss = loss_fn(output, target_var)

    loss.backward()
    optimizer.step()

    correct = 0
    total = 0

    # Check how accuracy progresses 
    
    ## TODO: VISUALIZATION of confusion matrix here?
    if i % 5 == 0:
        print "============== Iteration ", i
        y_test = target_var.cpu().data.numpy()
        y_pred_all = output.cpu().data.numpy()
        y_pred = np.argmax(y_pred_all, axis=1)

        correct += (y_pred == y_test).sum()
        total += y_pred.shape[0]

        cnf_matrix = confusion_matrix(y_test, y_pred)
        print "Loss: ", loss.data[0], ", Acc: ", (correct / float(total))
        print cnf_matrix

============== Iteration  0
Loss:  2.30534148216 , Acc:  0.08984375
[[ 0  0  0  7  0  0  0 37  0  0]
 [ 0  0  0  1  0  0  0 43  0  0]
 [ 0  0  0  6  0  0  0 48  0  0]
 [ 0  0  0  6  0  0  0 44  0  0]
 [ 0  1  0  5  3  0  0 41  1  0]
 [ 0  0  0  1  0  0  0 60  0  0]
 [ 0  0  0  5  1  0  0 50  0  0]
 [ 0  1  0  4  1  0  1 37  0  0]
 [ 0  0  0  4  1  0  0 52  0  0]
 [ 0  0  0  3  0  0  0 48  0  0]]
============== Iteration  5
Loss:  2.28909850121 , Acc:  0.09765625
[[ 0  0  0  0 11  0  0 50  0  0]
 [ 0  0  0  0  0  0  0 48  0  0]
 [ 0  0  0  4  8  0  1 42  0  0]
 [ 0  0  0  2  6  0  2 29  0  0]
 [ 0  0  0  0 16  0  0 33  4  0]
 [ 0  0  0  2  2  0  1 50  0  0]
 [ 0  0  0  2  9  0  3 45  1  0]
 [ 0  0  0  2 12  0  1 29  0  0]
 [ 0  0  0  1  6  0  2 40  0  0]
 [ 0  0  0  1  6  0  0 41  0  0]]
============== Iteration  10
Loss:  2.26434445381 , Acc:  0.1015625
[[ 0  0  0  0  6  0  0 45  0  0]
 [ 0  0  0  0  1  0  0 63  0  0]
 [ 0  0  0  0  3  0  1 41  0  0]
 [ 0  0  0  0  6  0  0 37  0  0]
 [

============== Iteration  105
Loss:  2.04841327667 , Acc:  0.236328125
[[ 2  8  0  1  5 17  6  1  7  4]
 [ 0 39  0  0  0  4  1  0  0  0]
 [ 2  4  2  1 10  9  5  1  7  6]
 [ 4  0  4  0 22 10 11  4  8  7]
 [ 0  3  0  1 43  2  1  3  1  4]
 [ 0 15  1  0  3 17  2  0  1 10]
 [ 0  3  0  0 14 15  4  0  5  3]
 [ 1  0  2  0 29  5  2  3  1  3]
 [ 1  1  1  1 21  2  6  3  8  7]
 [ 2  3  0  0 10 20  5  1  8  3]]
============== Iteration  110
Loss:  2.05128645897 , Acc:  0.25
[[ 0  4  1  7  2 13  2  5  3  8]
 [ 0 49  1  0  0  3  0  0  0  3]
 [ 0  6  7  4  4 14  1  8  3 12]
 [ 0  2  1  6  8  5  0 14  4  7]
 [ 2  0  0  7 10  2  4 15  5  1]
 [ 1 14  1  2  1 19  0  3  2  9]
 [ 0  4  0  3  5 18  3  8  4  1]
 [ 1  1  1  2  7  1  1 15  4  3]
 [ 1  3  4 13 11  9  4 11  9  5]
 [ 1  6  2  5  4 17  2  5  3 10]]
============== Iteration  115
Loss:  1.96636414528 , Acc:  0.26953125
[[ 2  2  6  7  1 15  5  9  1  0]
 [ 0 46  1  0  0  6  0  0  0  0]
 [ 0  5  6 14  1 13  1  8  2  0]
 [ 7  0  5  9  1  5  4 14  2  0]
 

============== Iteration  210
Loss:  1.92919135094 , Acc:  0.265625
[[15  6 18  0  2 17  3  1  4  1]
 [ 3 38  0  0  0  5  0  0  0  0]
 [11  3 15  1  6  5  0  3  2  5]
 [11  5 14  3 13  3  1  5  1  0]
 [ 7  0  1  2 27  0  0  6  4  1]
 [ 4 13  7  1  1 13  1  0  0  0]
 [14  2 10  4  7 12  4  7  5  0]
 [ 3  0  8  0 15  2  1 13  3  0]
 [13  1  4  1  6  8  3  3  7  0]
 [ 5  5 16  4  2 10  1  2  2  1]]
============== Iteration  215
Loss:  1.87746787071 , Acc:  0.314453125
[[ 2  3  6  4  0 11  1 15  4  1]
 [ 0 50  1  0  0  4  0  0  2  0]
 [ 6  5 12  8  1  8  0 14  5  0]
 [ 7  0 11 11  3  6  0  8  9  2]
 [ 2  0  2  2 17  0  2 15  4  0]
 [ 3 15  4  0  0 24  0  1  1  2]
 [ 5  1  4  2  3 11  3 11  7  0]
 [ 3  1  3  1  5  0  0 30  2  0]
 [ 2  4  6  8  3  3  1  7  9  3]
 [ 3  4 11  3  1 17  2 11  5  3]]
============== Iteration  220
Loss:  1.8610342741 , Acc:  0.296875
[[ 3  2  6  1  2 11  4  6  5  4]
 [ 0 48  1  0  0  6  0  0  0  2]
 [ 3  3 22  1  1  6  0  7  2  5]
 [ 4  1  7  3  1  8  2  8  7  2]


============== Iteration  315
Loss:  1.82586026192 , Acc:  0.3125
[[17  1  2  4  5 15  5  4  0  1]
 [ 2 43  0  0  0  5  1  0  1  0]
 [10  1  1  1  4  6  6  0  2  3]
 [14  0  3  6  5  6 10  5  6  3]
 [ 1  0  0  1 35  0  4  4  3  0]
 [ 6 14  1  2  0 22  3  1  1  2]
 [ 4  1  2  1 13  4 11  4  6  5]
 [ 4  2  2  0 26  3  3 15  2  1]
 [ 9  1  2  4  8  2 14  0  8  3]
 [17  4  2  1  2 14  5  4  3  2]]
============== Iteration  320
Loss:  1.90803027153 , Acc:  0.30859375
[[ 8  3 11  6  4 12  6  0  3  2]
 [ 0 43  2  1  0  6  1  0  1  0]
 [ 8  4 15  2  2  6  2  3  2  1]
 [ 8  1  8  7  2 11  2  3  7  2]
 [ 2  0  2  2 23  2  3  6  4  0]
 [ 5 10  1  0  0 22  1  0  5  1]
 [ 5  0  2  6  7 10  6  7  9  4]
 [ 5  1  4  5 23  2  2 15  4  2]
 [ 3  2 10  3  5  5  4  6 14  2]
 [10  4  6  5  2  7  2  2  2  5]]
============== Iteration  325
Loss:  1.83211553097 , Acc:  0.291015625
[[ 4  2 27  3  1 11  2  6  9  8]
 [ 1 36  0  0  0  2  0  0  1  0]
 [ 1  6 16  2  1  4  0  8  5  6]
 [ 1  2 15  2  1  1  0  9  1  1]

============== Iteration  420
Loss:  1.7370351553 , Acc:  0.3515625
[[ 3  1 12  2  2  9  3 10  2  4]
 [ 1 58  1  1  0  8  0  0  0  1]
 [ 5  3 22  8  2  8  0  2  1  3]
 [ 4  0 13 10  2  4  2  8  9  5]
 [ 0  0  1  4 28  0  1  9  3  1]
 [ 2  8  6  0  0 28  2  0  2  3]
 [ 1  0  5  2  7 11  6 12  9  1]
 [ 1  2  4  7 12  0  4 15  1  1]
 [ 0  1  7  4  4  1  6  5  9  1]
 [ 2  3  6  4  3 14  2  4  7  1]]
============== Iteration  425
Loss:  1.79805922508 , Acc:  0.341796875
[[ 8  0 10  2  0 10  6  4  2  8]
 [ 1 37  0  0  0  8  0  0  1  1]
 [ 3  2 22  2  2 14  2  1  5  5]
 [ 1  0 11 11  0  4  4  3  7  3]
 [ 0  0  0  1 27  1  1 10 10  0]
 [ 0 10  9  1  0 24  0  2  3  1]
 [ 3  0  7  5  7 12  6  2 11  1]
 [ 0  1  3  7 11  2  5 16  6  1]
 [ 4  2  6  2  6  5  4  2 17  1]
 [ 6  2  7  3  2 13  4  4  9  7]]
============== Iteration  430
Loss:  1.79742324352 , Acc:  0.34375
[[11  2  3  6  2 14  3  2  2  5]
 [ 0 50  0  1  0  9  1  0  1  0]
 [ 6  3 10  4  5 13  0  3  4  2]
 [ 8  0  8 12  3  4  2  9  7  1]


============== Iteration  525
Loss:  1.75443983078 , Acc:  0.380859375
[[ 8  1  9  6  4 11  4  1  1  2]
 [ 2 38  0  0  0 11  0  0  1  1]
 [ 2  1 12  9  4  9  0  4  8  3]
 [ 1  3  9 18  2  5  0  2 10  3]
 [ 2  0  1  3 33  3  1  4 10  1]
 [ 1  5  4  2  0 35  2  2  3  1]
 [ 0  0  9  8  7  1  6  5 11  5]
 [ 0  0  4  4 18  0  0  8  7  1]
 [ 1  2  5 11  3  1  2  1 25  2]
 [ 1  2 10  6  0 11  1  1  3 12]]
============== Iteration  530
Loss:  1.7477697134 , Acc:  0.34375
[[ 9  0  5  9  2 10  6  5  8  4]
 [ 0 43  0  0  0 13  1  0  1  0]
 [ 2  0 16  3  1  8  3  2  4  9]
 [ 2  3 14 11  2  3  7  5 10  2]
 [ 0  0  0  2 15  2  3 19  3  1]
 [ 3  8  6  0  0 32  3  0  0  5]
 [ 0  0  4  5  1  4  7  7  9  3]
 [ 0  0  3  2  7  2  4 26  2  3]
 [ 1  1  9  8  6  2  4  6 13  2]
 [ 3  0  8  3  0 13  8  5  2  4]]
============== Iteration  535
Loss:  1.74234855175 , Acc:  0.353515625
[[10  0  6  1  2  5  3  5  3  3]
 [ 1 51  1  0  0  7  1  0  3  0]
 [ 7  0 22  1  4 10  2  5  5  1]
 [ 5  0 15  6  0  2  5 10  6  1

============== Iteration  630
Loss:  1.73035919666 , Acc:  0.390625
[[15  1  6  4  1  6  7  3  5  2]
 [ 0 42  2  0  0 12  0  0  1  0]
 [ 4  1 12  7  1  8  2  2  6  2]
 [ 3  0  6 19  2  2  2  4  7  4]
 [ 1  1  1  3 24  1  4  9  9  1]
 [ 3  3  5  1  0 23  1  0  1  1]
 [ 4  0  3  9  4  4  7 14 11  3]
 [ 0  0  6  4  6  1  0 29  4  1]
 [ 3  3  3  8  2  2  5  5 24  4]
 [ 6  2  5  6  2 11  5  6  2  5]]
============== Iteration  635
Loss:  1.71280133724 , Acc:  0.36328125
[[15  0  4  6  5 11  9  1  5  7]
 [ 1 47  1  0  0  9  0  0  1  0]
 [ 2  1 16  9  1  8  0  2  5 10]
 [ 0  0  9  9  5  2  5  1  9  4]
 [ 2  1  1  2 16  0  3  6  7  2]
 [ 1  4  2  1  1 31  0  0  1  2]
 [ 4  0  7  3  7  6  8  6 13 12]
 [ 0  0  2  6  8  1  3  7  3  4]
 [ 0  1  4  7 13  1  0  0 23  2]
 [ 4  1  6  3  2 13  5  3  7 14]]
============== Iteration  640
Loss:  1.68953001499 , Acc:  0.384765625
[[16  0  4  3  3  7  0  3  1  2]
 [ 1 36  0  0  0  3  0  0  0  0]
 [ 8  1 18  6  8  7  0  2  3  7]
 [ 3  1  9 11  3  2  5  2  6  

============== Iteration  735
Loss:  1.70743191242 , Acc:  0.388671875
[[16  3 10  9  2  4  2  3  2  2]
 [ 0 29  4  0  0 10  0  0  0  0]
 [ 4  2 24  9  5 11  1  3  4  1]
 [ 1  2 25 23  2  3  3  1  6  1]
 [ 0  0  4  1 22  0  1  6  2  2]
 [ 1  5  6  3  0 31  1  1  2  6]
 [ 1  0  6  8  6  6  9  5  4  1]
 [ 1  0  6  5 16  2  1 22  0  0]
 [ 1  0 10  6  4  1  3  3 13  1]
 [ 2  1  9  9  4  4  5  3  3 10]]
============== Iteration  740
Loss:  1.65432071686 , Acc:  0.388671875
[[19  0 10  5  1  1  7  3  2  1]
 [ 0 42  2  0  0  4  1  0  0  1]
 [ 4  2 26  5  2 10  0  1  4  9]
 [ 2  0 10 14  1  6  3  4  4  2]
 [ 0  0  2  6 17  0  2  9  8  3]
 [ 1 10  5  1  2 34  3  2  2  3]
 [ 1  0  3  6  6  3  7  7  2  9]
 [ 2  1  6  4 11  1  6 22  3  5]
 [ 0  4  9 10  4  0  2  0 12  1]
 [ 1  0 15  3  1 10  6  4  1  6]]
============== Iteration  745
Loss:  1.66077959538 , Acc:  0.396484375
[[15  0 11  8  0  3  2  6  2  7]
 [ 0 43  2  0  0  8  1  0  1  0]
 [ 3  1 11  6  1 11  0  7  8  4]
 [ 0  1 11 10  3  1  1  9 

============== Iteration  840
Loss:  1.58466804028 , Acc:  0.451171875
[[21  0  7  9  1  5  2  2  2 11]
 [ 1 37  0  0  0  5  0  0  0  0]
 [ 3  1  9  8  3 12  0  3  4  5]
 [ 0  1  6 30  2  3  2  5  3  6]
 [ 1  1  1  5 34  0  0 12  5  3]
 [ 4  8  3  2  1 30  0  0  3  2]
 [ 3  0  3  9  1  2 17 11  4  7]
 [ 0  0  4  4  5  1  0 21  3  2]
 [ 0  2  0 10  4  2  2  2 12  1]
 [ 3  1  6  6  0  7  6  2  5 20]]
============== Iteration  845
Loss:  1.62520468235 , Acc:  0.44140625
[[13  1  4  5  6  4  5  3  1  1]
 [ 0 35  2  0  0  3  0  0  0  0]
 [ 5  0 22  7  3  7  0  2  3  4]
 [ 0  0 12 20  5  2  7  1  3  1]
 [ 2  0  2  4 29  1  2  9  4  1]
 [ 1  4  2  4  1 28  3  1  3  3]
 [ 0  0  4  6 15  3 11  7  6  4]
 [ 1  3  5  4 15  0  1 38  1  0]
 [ 0  1  5 11  6  0  3  2 16  0]
 [ 2  0 10  8  3  5  5  5  1 14]]
============== Iteration  850
Loss:  1.67174911499 , Acc:  0.3984375
[[20  1  9  7  0  5  4  3  2  3]
 [ 0 45  2  0  0  4  0  0  0  0]
 [ 3  0 22  2  1 15  2  4  6  2]
 [ 1  2  9  9  6  1  3  5  8 

============== Iteration  945
Loss:  1.64383065701 , Acc:  0.380859375
[[13  1  7  5  4  5  9  2  2  5]
 [ 0 40  0  1  1  5  0  0  2  2]
 [ 5  0 19  4  2  9  3  2  3  4]
 [ 5  0  6 12  2  1  8  6  5  3]
 [ 0  0  3  6 28  1  5 14  7  0]
 [ 3  8  3  1  0 29  0  0  1  5]
 [ 2  0  5  2  9  3 12  4  8  6]
 [ 0  1  2  3 12  2  4 16  4  1]
 [ 1  0  4  5  5  2  5  6 19  5]
 [ 6  1 13  5  2  8  2  2  1  7]]
============== Iteration  950
Loss:  1.52253508568 , Acc:  0.482421875
[[26  0  4  6  0  4  2  1  3  3]
 [ 0 46  2  0  0  5  0  1  0  0]
 [ 5  0 17  6  5  6  1  2  1  6]
 [ 0  2  7 16  4  0  6  0  9  4]
 [ 0  1  0  5 33  0  1  6  8  0]
 [ 3  7  6  2  2 38  1  0  6  2]
 [ 3  0  6  7  4  4 16  2  8  5]
 [ 0  0  1  9 14  1  0 17  1  1]
 [ 0  1  2  9  4  0  3  2 27  3]
 [ 3  1  4  8  0  6  2  2  4 11]]
============== Iteration  955
Loss:  1.57066714764 , Acc:  0.392578125
[[18  0  4  6  5  3  5  8  4  2]
 [ 0 36  0  0  0  3  0  0  0  1]
 [ 3  1 15 10  3 10  1  2  2  6]
 [ 2  0  2 11  0  2  1  4 

============== Iteration  1050
Loss:  1.66033744812 , Acc:  0.375
[[25  0  6  4  6  5  7  6  1  4]
 [ 0 31  0  0  0  8  0  0  0  0]
 [ 8  1 18  7  0 13  2  1  3  4]
 [ 5  1  6  9  2  3  5  9  7  6]
 [ 1  0  2  4 18  0  0  9  6  1]
 [ 3  6  5  2  1 28  1  1  3  4]
 [ 6  0  7  3  5  6  8  8  3  4]
 [ 4  0  3  8  8  1  1 21  4  3]
 [ 1  1  1  9  0  4  2  2 22  1]
 [ 9  0 10  4  2 12  4  1  4 12]]
============== Iteration  1055
Loss:  1.61362600327 , Acc:  0.431640625
[[12  0  9  7  4  3  7  0  2  9]
 [ 0 46  1  0  0  6  0  0  3  2]
 [ 1  1 21  4  2  6  1  4  1  7]
 [ 1  1  3 13  5  4  3  2  9 10]
 [ 1  1  1  9 24  1  2 11  4  0]
 [ 2  6  4  2  0 23  0  0  4  4]
 [ 2  0  3  5  3  3 14 12  6  9]
 [ 0  2  4  2  9  0  0 22  3  3]
 [ 0  1  4 14  2  1  6  1 29  3]
 [ 1  1  3  6  1  5  4  0  2 17]]
============== Iteration  1060
Loss:  1.54632771015 , Acc:  0.427734375
[[21  0  9  6  4  1  3  2  3  3]
 [ 0 40  2  0  0  6  0  0  0  2]
 [ 2  1 13  8  1  3  1  0  6  7]
 [ 0  0  4 17  8  2  4  1 14 

============== Iteration  1155
Loss:  1.57496607304 , Acc:  0.4609375
[[19  1  2  7  3  5  3  4  2  7]
 [ 1 48  1  0  0  6  1  0  0  1]
 [ 3  0 24  5  5 11  1  3  1  8]
 [ 0  0  7 24  3  0  3  3  8 10]
 [ 2  0  1  4 23  1  2  9  7  1]
 [ 1  6  2  2  2 23  2  0  0  2]
 [ 3  0  4  7  7  8  8  7  7  6]
 [ 1  1  2  1  8  1  0 24  2  7]
 [ 2  1  1  8  3  2  0  4 26  4]
 [ 0  3  5  1  2  3  3  0  3 17]]
============== Iteration  1160
Loss:  1.52171373367 , Acc:  0.44921875
[[25  0  9 10  2 11  0  2  3  8]
 [ 1 44  0  0  0  8  0  0  0  0]
 [ 1  0 18  9  1 16  2  3  3  4]
 [ 1  0  8 15  5  2  3  4  3  2]
 [ 1  0  0  2 26  0  0 13  2  3]
 [ 4  6  3  2  0 20  0  0  1  2]
 [ 6  0  3  8  6  3 12  8  4  8]
 [ 1  1  6  2  5  1  1 30  3  3]
 [ 2  1  2  9  2  0  0  1 24  1]
 [ 4  1  6  5  3  5  4  4  3 16]]
============== Iteration  1165
Loss:  1.508425951 , Acc:  0.46484375
[[18  0  8  5  4  6 11  3  2  4]
 [ 0 54  0  0  0  4  0  0  0  1]
 [ 3  0 16  2  1  9  1  3  1  4]
 [ 1  1  5  8  3  2  4  3 12 

============== Iteration  1260
Loss:  1.61217141151 , Acc:  0.42578125
[[13  0  7  3  1  7  1  2  4  6]
 [ 2 35  0  0  0  4  0  0  1  0]
 [ 6  1 15 10  2  8  1  4  2  3]
 [ 4  2  8 15  3  4  1  3  5  6]
 [ 0  0  1  6 35  1  0 11  5  2]
 [ 0  9  5  3  0 26  1  3  1  3]
 [ 1  0  5 10  8  2 15  4  3  3]
 [ 0  0  2  7  9  3  1 26  1  2]
 [ 0  0  2 14  3  3  2  5 24  3]
 [ 4  0 10  5  0  8  5  4  3 14]]
============== Iteration  1265
Loss:  1.56550359726 , Acc:  0.44140625
[[19  1  5  6  2  3  4  1  3  7]
 [ 1 33  0  0  0  6  0  0  0  1]
 [ 5  0 20  9  4  8  1  2  7  4]
 [ 2  0  4 16  7  1  5  6 11  5]
 [ 0  0  0  5 30  0  2  6  5  1]
 [ 3  8  1  0  0 29  1  1  1  5]
 [ 1  0  2  3  4  8 18  3  5  5]
 [ 2  1  2  5 22  1  2 22  2  1]
 [ 2  0  1 10  5  2  3  2 25  3]
 [ 3  0  5  7  1  5  3  1  4 14]]
============== Iteration  1270
Loss:  1.51382803917 , Acc:  0.43359375
[[19  1  6  9  3  6  3  7  2  2]
 [ 1 40  0  0  0  7  0  0  0  0]
 [ 4  0 19  5  2  7  1  2  3  6]
 [ 1  0  9 20  2  3  7  3 

============== Iteration  1365
Loss:  1.46749472618 , Acc:  0.447265625
[[26  0  3  6  1  2  1  3  3  7]
 [ 2 46  0  0  0  9  0  0  1  0]
 [ 3  2 16  9  0 11  0  2  1  6]
 [ 3  1  5 23  1  1  4  4  7  7]
 [ 0  1  1  8 20  2  1  9  6  4]
 [ 1  6  2  2  1 23  0  0  3 11]
 [ 4  0  5  6  4  2 13  7  2  6]
 [ 0  0  2  6  8  0  3 26  4  4]
 [ 2  0  2  6  3  0  1  3 21  5]
 [ 2  0 10  6  0  7  4  2  4 15]]
============== Iteration  1370
Loss:  1.48740005493 , Acc:  0.466796875
[[21  0  2  6  1  6  5  3  2  3]
 [ 1 44  1  0  0  9  0  0  0  1]
 [ 3  0 23  9  2  8  0  2  2  5]
 [ 5  0  5 15  2  1  2  1  6  0]
 [ 0  0  0  2 22  1  0 10  7  1]
 [ 5  8  6  3  0 25  0  0  2  2]
 [ 3  0  3  5  2  5 14  4  4  5]
 [ 1  1  5  5  6  2  2 30  1  1]
 [ 2  1  5 11  0  3  3  2 27  1]
 [ 3  1 10  9  0 15  6  5  1 18]]
============== Iteration  1375
Loss:  1.55247712135 , Acc:  0.419921875
[[15  2  5  2  1  4  6  4  0  4]
 [ 2 43  1  0  0  6  1  0  2  2]
 [ 3  0 18  6  2 10  3  2  2  5]
 [ 3  0  5 18  2  6  5 

============== Iteration  1470
Loss:  1.47614860535 , Acc:  0.474609375
[[19  0  5  3  2  3  5  6  1  3]
 [ 0 43  0  0  0 10  0  0  0  0]
 [ 6  3 22  6  3 10  0  2  2  2]
 [ 1  0  2 25  1  1  5  5 11  5]
 [ 1  0  0  3 20  0  1 10  5  1]
 [ 1  3  3  3  0 41  0  0  1  6]
 [ 1  0  3  8  7  4 18 10  6  4]
 [ 1  0  0  6  8  1  4 16  0  3]
 [ 1  1  2 16  3  1  1  3 26  2]
 [ 3  0  5  7  0  6  8  0  3 13]]
============== Iteration  1475
Loss:  1.50628638268 , Acc:  0.47265625
[[19  1  6  8  0  3  7  3  4  8]
 [ 0 53  1  1  0  8  0  0  0  0]
 [ 5  3 14  8  5  8  1  0  6  3]
 [ 0  1  4 17  1  3  5  0  9  3]
 [ 0  1  0  8 24  0  4  6  5  1]
 [ 0  8  2  3  0 38  0  0  2  4]
 [ 2  0  2  8  4  4 11  6  4  5]
 [ 2  0  3  2  6  0  5 19  3  0]
 [ 2  1  0  9  4  0  4  3 20  1]
 [ 1  1  9  5  2  3  6  1  3 27]]
============== Iteration  1480
Loss:  1.43907284737 , Acc:  0.486328125
[[12  1  5  6  1  2  2  5  2  2]
 [ 0 50  0  0  0  3  0  0  0  0]
 [ 2  1 24  7  2 11  1  3  3  5]
 [ 2  0  6 26  2  1  1  

============== Iteration  1575
Loss:  1.53185880184 , Acc:  0.494140625
[[15  1  4  5  1  7  3  4  3  1]
 [ 0 43  0  0  0  9  1  0  1  1]
 [ 3  0 20  1  1  8  5  5  2  4]
 [ 1  0  4 18  3  1  5  6  6  3]
 [ 0  0  3  4 30  2  2 10 10  0]
 [ 2  5  4  0  1 23  1  0  1  5]
 [ 0  0  1 10  7  3 20  6  4  4]
 [ 2  2  1  5  8  0  1 29  4  1]
 [ 0  2  3  6  6  2  2  3 34  3]
 [ 2  0  2  6  2  3  5  4  0 21]]
============== Iteration  1580
Loss:  1.47240495682 , Acc:  0.48828125
[[24  2  8  1  0  7  1  4  2  5]
 [ 2 41  2  0  0  3  0  0  1  0]
 [ 1  1 21  7  1  8  1  1  3  4]
 [ 1  0  3 13  3  2  3  7 10  5]
 [ 0  1  1  4 21  0  4  9  5  1]
 [ 0 14  4  2  0 31  0  0  1  3]
 [ 1  0  3  6  3  2  8  5  7 11]
 [ 4  1  2  5  3  0  1 37  0  1]
 [ 0  0  2  7  3  2  2  4 36  4]
 [ 5  0  8  5  0  4  5  3  5 18]]
============== Iteration  1585
Loss:  1.5049405098 , Acc:  0.46875
[[20  0  7  5  1  3  8  2  2  7]
 [ 1 35  0  0  0  4  0  0  0  0]
 [ 6  0 19 11  2 10  0  6  5  8]
 [ 0  0 10 17  0  1  5  2  7 

============== Iteration  1680
Loss:  1.43155395985 , Acc:  0.46875
[[14  0  5  3  2  5  5  0  3  3]
 [ 1 46  1  0  0 10  0  0  0  0]
 [ 4  0 16  3  2  8  1  1  4  7]
 [ 3  0  3 20  2  0  6  3 13  9]
 [ 1  0  1  5 26  1  1 11  3  1]
 [ 4  7  3  1  0 35  0  1  1  1]
 [ 4  0  1  3  5  3 15  7  5  5]
 [ 1  3  2  8  6  0  3 35  3  4]
 [ 0  0  0  8  5  0  6  0 18  4]
 [ 1  3 11  3  0  6  2  5  6 15]]
============== Iteration  1685
Loss:  1.41967499256 , Acc:  0.478515625
[[32  0  0  5  2  6  1  5  0  2]
 [ 1 55  0  0  0  2  0  0  0  2]
 [ 7  4 15  7  2  4  3  4  1  6]
 [ 0  0  4 23  1  2  4  6  7  8]
 [ 0  0  0  8 25  0  0  9  7  0]
 [ 1  9  3  0  1 24  3  1  3  3]
 [ 1  0  7  5  7  2 11  7  5  4]
 [ 0  1  2  7  8  0  4 25  1  1]
 [ 0  2  1 13  3  0  3  2 26  4]
 [ 3  1  9  7  2  3  4  2  2  9]]
============== Iteration  1690
Loss:  1.42499244213 , Acc:  0.50390625
[[25  1  2  8  3  7  4  5  4  2]
 [ 1 42  0  0  0  5  0  0  0  1]
 [ 0  1 18  4  2  4  0  1  5  2]
 [ 5  1  1 16  1  0  2  3  9

============== Iteration  1785
Loss:  1.39652335644 , Acc:  0.515625
[[23  1  6  1  1  6  5  5  4  3]
 [ 1 33  0  0  0  7  1  0  1  1]
 [ 1  0 27  5  1  2  1  0  3  6]
 [ 4  0  5 15  1  1  3  3  7  4]
 [ 0  1  2  2 35  0  4  5  6  5]
 [ 2  6  4  0  1 33  0  0  1  1]
 [ 3  0  6  4  1  4 21  3  6  8]
 [ 0  0  5  6 10  1  5 31  1  3]
 [ 0  1  1  5  4  0  2  1 31  7]
 [ 0  1  5  6  1  6  6  3  3 15]]
============== Iteration  1790
Loss:  1.47414469719 , Acc:  0.466796875
[[28  1  5  4  3  6  1  6  2  8]
 [ 2 36  0  0  0  7  1  0  0  0]
 [ 1  0 21  7  1  4  0  4  1 12]
 [ 2  0  7 16  4  3  3  4  7  7]
 [ 2  0  0  5 30  0  0 14  1  2]
 [ 2  2  6  0  1 25  0  2  1  2]
 [ 4  0  2  8  1  8  9  8  7  6]
 [ 1  1  2  3  4  0  0 24  1  2]
 [ 1  0  1 14  3  0  0  2 30  3]
 [ 3  1 19  5  0  2  3  4  1 20]]
============== Iteration  1795
Loss:  1.47057008743 , Acc:  0.484375
[[17  2 10  6  2  6  3  3  7  7]
 [ 1 52  0  0  0  6  0  0  3  0]
 [ 2  0 19  2  6  6  0  6  2  6]
 [ 1  0  3 15  1  2  2  5 19 

============== Iteration  1890
Loss:  1.4918371439 , Acc:  0.478515625
[[15  1  5  5  3  3  5  3  4  1]
 [ 0 36  1  0  0  6  0  0  0  2]
 [ 1  0 12 11  2 11  2  1  2  4]
 [ 1  2  1 32  4  1  4  0  7  2]
 [ 2  0  0  5 33  1  7  4  5  2]
 [ 2  8  6  0  0 23  2  0  4  5]
 [ 1  0  2  7  5  5 13  5  7  8]
 [ 0  0  4  9  5  2  7 32  3  2]
 [ 1  1  1  7  2  2  3  1 28  4]
 [ 1  1  4  9  0  2  2  2  4 21]]
============== Iteration  1895
Loss:  1.46368539333 , Acc:  0.470703125
[[20  0  5  5  1  5  2  4  0  4]
 [ 2 36  0  0  0 11  1  0  0  0]
 [ 3  1 18 11  3  6  3  0  1  4]
 [ 2  2  6 22  6  2  6  3  5  7]
 [ 0  1  1  3 30  0  4  7  1  2]
 [ 2  6  3  1  1 34  2  0  1  0]
 [ 2  0  1  5  3  4 15  9  2  4]
 [ 1  0  3  3 16  0  4 29  2  2]
 [ 0  1  0 12  6  2  4  3 19  3]
 [ 4  1 10  7  2  2  4  3  0 18]]
============== Iteration  1900
Loss:  1.4942920208 , Acc:  0.45703125
[[17  0  6  6  0  5  5  6  5  3]
 [ 1 40  0  0  0 12  0  0  1  1]
 [ 3  1 24  5  1 14  1  5  3  7]
 [ 3  1  5 17  1  2  2  4 

============== Iteration  1995
Loss:  1.36139905453 , Acc:  0.501953125
[[20  0  3 11  0  5  3  2  1  3]
 [ 1 48  2  1  0  8  0  0  1  2]
 [ 3  1 23  6  1  4  1  6  3  8]
 [ 0  0  7 10  2  1  5  5  8  4]
 [ 1  1  1  2 30  0  1 10  2  3]
 [ 0  6  3  1  0 29  2  0  0  3]
 [ 4  1  3  5  0  4 19  9  9  4]
 [ 0  0  6  6  9  2  2 33  1  6]
 [ 2  1  1  8  3  2  2  0 22  0]
 [ 1  0 10  3  0  1  1  2  3 23]]
============== Iteration  2000
Loss:  1.41802299023 , Acc:  0.486328125
[[24  0  2  1  3  4  1  4  4  2]
 [ 2 51  1  0  0 12  0  0  0  1]
 [ 2  0 24  4  2  4  0  3  2  9]
 [ 1  1  6 13  4  0  2  6 13  8]
 [ 0  1  0  5 31  0  3 11  5  0]
 [ 1  5  7  0  1 14  0  0  2  1]
 [ 4  1  4  9  7  3 14  9  5  5]
 [ 1  1  2  2  6  1  0 30  4  5]
 [ 1  1  5  8  2  2  0  1 23  1]
 [ 3  1  5  5  1  6  2  1  3 25]]
============== Iteration  2005
Loss:  1.49120247364 , Acc:  0.47265625
[[12  3  5  5  0  4  7  6  2  2]
 [ 1 38  3  0  0  6  0  0  1  1]
 [ 4  1 24  3  0 12  2  2  3  6]
 [ 7  1  6 14  2  0  3  

============== Iteration  2100
Loss:  1.40336370468 , Acc:  0.51953125
[[14  0  2  4  1  3  2  4  3  2]
 [ 1 39  0  0  0  2  2  0  2  0]
 [ 3  0 19  5  1  2  0  1  0  2]
 [ 1  0  7 24  3  1  5  3  4  3]
 [ 0  0  1  5 34  1  0 13  2  0]
 [ 2  8  4  3  0 35  0  2  0  4]
 [ 2  0  2  8  9  5 12 12  6  4]
 [ 2  0  3  6  9  0  2 36  4  2]
 [ 0  0  0 10  7  1  3  2 33  2]
 [ 2  0  8 12  0  5  2  1  1 20]]
============== Iteration  2105
Loss:  1.39956688881 , Acc:  0.51171875
[[16  2  4  2  2  4  1  7  2  6]
 [ 1 49  0  0  0  4  0  0  1  0]
 [ 3  2 24  5  3  7  1  2  5  6]
 [ 0  1  2 21  2  3  5 12  9  4]
 [ 0  1  0  1 27  1  2  6  5  1]
 [ 3  4  2  5  1 27  1  1  4  6]
 [ 2  0  1  4  4  3 17  4  6  3]
 [ 1  0  5  5  7  0  1 27  1  1]
 [ 2  0  1  6  4  3  2  3 35  2]
 [ 1  1  2  5  1  5  6  4  2 19]]
============== Iteration  2110
Loss:  1.42459928989 , Acc:  0.498046875
[[21  4  8  5  2  6  2  3  4  5]
 [ 1 38  0  0  0  5  1  0  1  1]
 [ 0  1 28  4  1  3  1  1  5  4]
 [ 1  0  6 18  0  0  2  3

============== Iteration  2205
Loss:  1.44846427441 , Acc:  0.474609375
[[22  1  7  9  2  2  4  4  3  1]
 [ 0 42  1  0  0  3  0  0  0  1]
 [ 4  1 15  4  4  7  0  1  5  5]
 [ 4  1  8 18  2  0  1  5 10  5]
 [ 0  1  1  7 27  0  3  4  5  1]
 [ 4  3  3  4  2 35  0  1  0  1]
 [ 5  0  3  8  6  4 11  6  1 10]
 [ 3  1  5  1  5  0  2 31  1  5]
 [ 1  3  2  7  1  1  5  2 22  4]
 [ 3  1 10  4  2  3  3  5  1 20]]
============== Iteration  2210
Loss:  1.41302239895 , Acc:  0.49609375
[[18  1  5  7  1  3  5  1  5  5]
 [ 0 41  0  0  0  6  0  0  0  1]
 [ 1  1 29  4  2  3  1  3  2  7]
 [ 1  0  4 23  2  2  6  1  7 11]
 [ 0  0  0  3 29  2  3  7  1  1]
 [ 1  5  6  2  0 26  0  1  1  4]
 [ 1  0  4  4  6  3 15 10  4  3]
 [ 1  1  5  6  9  2  4 29  5  3]
 [ 1  2  2  7  2  1  3  3 25  3]
 [ 2  1 13  4  0  4  2  1  1 19]]
============== Iteration  2215
Loss:  1.40289390087 , Acc:  0.4921875
[[15  1  7  8  1  2  4  5  1  7]
 [ 2 36  0  0  0  4  0  0  0  1]
 [ 2  0 28  6  2  5  1  1  3  4]
 [ 1  1  8 26  2  1  4  5 

============== Iteration  2310
Loss:  1.35865712166 , Acc:  0.51171875
[[27  0  6  7  3  2 10  4  2  1]
 [ 2 42  1  1  0  5  0  0  0  2]
 [ 3  0 22  3  3  3  4  3  2  6]
 [ 3  0  4 14  3  0  5  5 10  5]
 [ 0  0  2  2 24  0  1  9  1  1]
 [ 3  8  9  0  0 30  1  0  0  6]
 [ 4  0  2  5  8  3 27  2  4  2]
 [ 2  0  5  4  6  1  4 32  2  3]
 [ 1  0  0  6  3  1  1  0 30  2]
 [ 6  2 10  6  0  2  0  2  0 14]]
============== Iteration  2315
Loss:  1.32851111889 , Acc:  0.54296875
[[32  1  3  3  2  6  5  1  2  0]
 [ 1 42  0  0  0  3  1  0  0  1]
 [ 3  1 11  4  3  6  3  5  3  4]
 [ 2  1  5 20  2  0  5  2 10  1]
 [ 0  0  0  6 36  1  3  5  3  3]
 [ 1  8  2  2  0 27  0  0  2  4]
 [ 5  0  2  4  2  1 21  2  4  2]
 [ 4  1  3  3  8  0  1 35  3  5]
 [ 2  2  2  9  4  1  1  5 31  0]
 [ 3  0  6  8  2  2  3  2  3 23]]
============== Iteration  2320
Loss:  1.39097070694 , Acc:  0.486328125
[[14  1  4  3  3  4  2  3  6  2]
 [ 0 35  1  0  0  3  0  0  0  3]
 [ 5  0 22  4  3  5  2  2  7  2]
 [ 2  0  5 21  3  0  4  5

============== Iteration  2415
Loss:  1.30174219608 , Acc:  0.55078125
[[33  2  4  7  3  5  5  4  0  4]
 [ 0 42  1  1  0  6  0  0  0  1]
 [ 2  2 31  9  0  2  1  6  2  4]
 [ 1  2  2 17  0  3  0  0  8  8]
 [ 0  0  1  5 31  0  3  5  5  2]
 [ 1  3  4  1  0 28  0  1  1  2]
 [ 6  0  4  6  1  5 17  5  2  6]
 [ 0  0  2  3  6  1  5 30  2  3]
 [ 2  1  2  5  2  2  2  3 31  4]
 [ 1  0  4  4  1  6  2  2  1 22]]
============== Iteration  2420
Loss:  1.34711277485 , Acc:  0.53515625
[[36  1  9  3  0  2  6  3  0  1]
 [ 1 53  1  1  0  3  1  0  0  0]
 [ 2  1 16  6  0  4  1  1  2  6]
 [ 0  1  2 21  3  0  6  6 11  5]
 [ 1  1  1  3 28  0  1  7  3  1]
 [ 1  6  6  0  1 27  0  0  1  4]
 [ 5  0  0  6  5  2 18 10  5  5]
 [ 0  0  6  3  9  0  2 30  3  4]
 [ 3  0  0  2  4  2  3  4 30  3]
 [ 2  2  7  4  2  7  1  0  1 15]]
============== Iteration  2425
Loss:  1.29891097546 , Acc:  0.568359375
[[12  1  4  2  2  5  7  1  3  3]
 [ 2 51  2  0  0  5  0  0  0  1]
 [ 5  0 22  3  1  8  5  0  6  4]
 [ 1  0  7 22  2  0  4  1

============== Iteration  2520
Loss:  1.34457969666 , Acc:  0.50390625
[[22  4  6  1  1  6  3  4  2  5]
 [ 0 41  1  0  0  3  0  0  0  1]
 [ 3  0 18  3  2  6  0  3  3  8]
 [ 4  0  9 18  2  1  0  3  6  6]
 [ 0  0  2  1 34  1  3  7  4  1]
 [ 2  9  6  1  0 31  3  1  2  2]
 [ 1  0  4  2  2  6 17  9  4  4]
 [ 0  0  4  2 10  0  1 32  0  3]
 [ 1  1  2  7  6  2  1  2 23  0]
 [ 2  1  7  7  1  7  9  4  1 22]]
============== Iteration  2525
Loss:  1.25872612 , Acc:  0.552734375
[[16  1  6  4  1  8  4  1  1  1]
 [ 0 47  3  1  0 11  1  0  0  0]
 [ 3  0 23  9  0  6  1  1  1  2]
 [ 2  0  7 16  1  1  2  0  9  4]
 [ 0  0  2  6 35  0  2 10  5  2]
 [ 0  3  6  1  1 44  0  0  1  0]
 [ 0  1  3  7  5  3 22  5  2  8]
 [ 1  1  3  1  1  2  4 35  1  2]
 [ 1  1  1  3  3  2  2  1 29  4]
 [ 4  1  6  6  1  7  3  1  1 16]]
============== Iteration  2530
Loss:  1.30005049706 , Acc:  0.53125
[[19  0  8  0  0  2  3  1  3  2]
 [ 0 43  2  0  0  4  0  0  0  1]
 [ 5  1 34  7  1  4  2  0  3  3]
 [ 3  0  8 14  2  1  7  0  8  4

============== Iteration  2625
Loss:  1.29239714146 , Acc:  0.52734375
[[28  0  9  6  2  3  6  3  1  5]
 [ 1 49  0  0  0  4  0  0  0  1]
 [ 3  0 21  7  1  7  1  2  3  9]
 [ 1  0  6 25  3  1  3  2  4  5]
 [ 0  1  0  7 23  0  0  7  4  3]
 [ 0  8  2  2  0 38  2  0  0  4]
 [ 3  0  1  9  0  4 16  3  2  7]
 [ 2  0  4  1  3  0  3 23  4  2]
 [ 0  2  0  6  2  1  3  2 22  1]
 [ 0  2 11  9  0  3  8  4  1 25]]
============== Iteration  2630
Loss:  1.3525749445 , Acc:  0.501953125
[[17  0  6  4  0  3  2  3  2  6]
 [ 0 43  1  0  0  3  1  0  1  0]
 [ 4  0 23  5  3  4  0  3  3  6]
 [ 0  0  6 28  6  2  2  4  7  5]
 [ 0  1  1  4 24  0  3  8  3  3]
 [ 1  9  8  2  2 25  1  0  2  3]
 [ 1  0  2  5  7  6 18  2  8 13]
 [ 0  0  3  5  6  0  1 32  1  6]
 [ 0  1  2 11  2  0  0  2 26  5]
 [ 2  0 12  1  0  4  2  1  1 21]]
============== Iteration  2635
Loss:  1.36771380901 , Acc:  0.515625
[[24  2  7  3  2  4  4  5  4  3]
 [ 0 43  2  1  0  5  2  0  0  0]
 [ 4  0 27  3  3  8  1  3  3  2]
 [ 0  1  6 19  2  2  3  5  7

============== Iteration  2730
Loss:  1.3922034502 , Acc:  0.494140625
[[27  0  7  7  1  3  3  3  1  4]
 [ 0 36  2  1  0  7  1  0  1  2]
 [ 3  1 16  4  2  8  0  3  1  8]
 [ 0  1  4 18  7  2  5  1  8 10]
 [ 1  0  1  2 40  2  2  6  6  1]
 [ 2  7  1  2  0 20  1  0  2  7]
 [ 2  0  3  8  6  1 19  5  3  5]
 [ 1  1  9  2 10  0  3 29  4  1]
 [ 0  0  5  4  3  0  6  0 33  0]
 [ 1  0  6  4  1  1  5  0  5 15]]
============== Iteration  2735
Loss:  1.3332504034 , Acc:  0.515625
[[23  2  5  9  3  6  4  3  0  8]
 [ 0 37  1  1  0  4  0  0  0  2]
 [ 5  0 22  7  1  3  2  1  0  6]
 [ 1  3  1 18  2  1  7  3  8  2]
 [ 0  0  2  6 33  0  2  7  3  3]
 [ 2  8  3  0  0 38  2  0  0  3]
 [ 3  1  2  4  2  3 18 10  1  6]
 [ 3  0  0  5  9  0  6 25  2  3]
 [ 0  2  3 12  6  1  2  0 30  1]
 [ 0  1  4  3  1  4  4  1  1 20]]
============== Iteration  2740
Loss:  1.33457756042 , Acc:  0.501953125
[[27  1  6  5  1  3  3  6  1  4]
 [ 1 37  2  0  0  5  0  0  0  0]
 [ 2  1 20  6  1  3  1  3  2  5]
 [ 2  0  2 16  2  0  5  5 14

============== Iteration  2835
Loss:  1.32904851437 , Acc:  0.51171875
[[21  0  8  6  2  3  3  3  2  3]
 [ 1 31  0  0  0  5  1  0  0  1]
 [ 7  0 22  5  2  6  1  5  0  7]
 [ 2  0  3 25  2  0  7  5  2  2]
 [ 0  0  0  4 29  1  2  5  1  1]
 [ 1  5  2  1  1 36  1  2  1  7]
 [ 1  0  6  8  2  4 20  6  1  7]
 [ 4  2  6  5  8  0  3 20  2  7]
 [ 0  0  1 14  3  2  2  0 28  4]
 [ 0  0  8  7  0  3  1  1  3 30]]
============== Iteration  2840
Loss:  1.27298617363 , Acc:  0.541015625
[[22  1  3  7  2  0  5  5  1  1]
 [ 3 46  0  0  0  2  0  0  0  2]
 [ 1  0 26  5  1  3  1  2  3  9]
 [ 4  0  4 25  3  2  3  5  7 11]
 [ 0  0  2  1 27  0  5  8  1  1]
 [ 4  4  4  0  1 36  1  1  2  1]
 [ 2  0  3  7  4  2 19  7  2  7]
 [ 1  2  3  4  1  0  2 29  1  4]
 [ 0  0  3  6  2  1  3  5 26  3]
 [ 5  0 10  4  0  3  5  1  0 21]]
============== Iteration  2845
Loss:  1.22068142891 , Acc:  0.560546875
[[16  0  1  6  1  6  3  1  3  4]
 [ 0 52  1  0  0  7  0  0  0  1]
 [ 6  2 20  3  4  4  0  0  3  8]
 [ 2  0  4 23  1  1  4  

============== Iteration  2940
Loss:  1.28029060364 , Acc:  0.5390625
[[20  0  8 11  2  5  6  7  2  2]
 [ 0 46  0  0  0  5  0  0  0  0]
 [ 4  1 26  3  2  6  0  1  0  3]
 [ 1  1  3 16  2  1  5  6  3  2]
 [ 1  1  1  2 34  0  2  7  5  2]
 [ 1  2  6  0  0 35  2  0  2  3]
 [ 0  0  2  7  3  2 16  8  3  4]
 [ 0  1  6  4  2  1  4 30  2  3]
 [ 1  1  2  6  3  1  3  0 34  2]
 [ 2  1  6  9  2  2  7  3  4 19]]
============== Iteration  2945
Loss:  1.29927158356 , Acc:  0.54296875
[[16  3  4  5  1  2  6  1  1  7]
 [ 1 53  0  0  0  9  0  0  0  0]
 [ 3  4 24  5  1  3  0  2  2  9]
 [ 0  2  5 12  2  1  2  0  7  7]
 [ 0  0  1  4 31  2  0  9  4  1]
 [ 0  6  9  0  2 35  0  0  0  3]
 [ 5  0  4  0  3  3 15  3  3 11]
 [ 2  0  2  4  4  1  4 40  3  5]
 [ 0  3  0  6  4  3  1  0 30  0]
 [ 1  1 10  6  1  2  1  1  1 22]]
============== Iteration  2950
Loss:  1.3355704546 , Acc:  0.501953125
[[20  1  5  3  3  5  4  5  2  3]
 [ 0 40  0  0  0  9  0  0  0  1]
 [ 6  0 19  6  2  6  3  0  7  4]
 [ 0  1  0 17  5  1 10  2  

============== Iteration  3045
Loss:  1.22627198696 , Acc:  0.583984375
[[25  0  7  4  2  5  4  2  0  5]
 [ 0 35  1  0  0  1  0  0  0  1]
 [ 2  1 23  5  1  1  2  2  2  2]
 [ 4  1  3 29  1  0  2  1  8  5]
 [ 0  1  1  5 43  0  3  9  2  2]
 [ 3  4  2  0  0 36  1  0  1  1]
 [ 2  0  7  5  2  2 17  2  2  4]
 [ 4  0  3  2  5  1  6 34  0  0]
 [ 1  1  2  4  1  0  0  1 35  3]
 [ 3  0 15  6  3  3  6  5  2 22]]
============== Iteration  3050
Loss:  1.29949092865 , Acc:  0.541015625
[[30  0  4  3  0  8  5  4  3  4]
 [ 0 44  1  0  0  4  0  0  1  1]
 [ 4  1 26  5  5  3  3  2  4  3]
 [ 1  0  3 23  6  2  4  2 13  4]
 [ 2  1  1  5 24  0  0  6  2  1]
 [ 4  4  4  0  0 37  0  0  0  2]
 [ 3  0  2  3  8  1 18  3  7  3]
 [ 1  1  6  2  7  0  1 28  0  1]
 [ 0  0  3  7  3  4  1  4 33  2]
 [ 2  0  9  5  2  0  7  2  0 14]]
============== Iteration  3055
Loss:  1.31895184517 , Acc:  0.525390625
[[16  3  3  3  3  2  1  4  2  1]
 [ 1 44  1  0  0  4  0  0  0  1]
 [ 3  1 14  6  1  4  0  2  0  3]
 [ 1  1  4 20  4  1  0 

============== Iteration  3150
Loss:  1.29186046124 , Acc:  0.525390625
[[20  1  3  3  0  4  8  3  3  4]
 [ 0 34  1  0  0  8  0  0  0  0]
 [ 3  0 26  1  2  9  1  4  5  5]
 [ 2  1  4 25  5  2  5  4  5  9]
 [ 1  0  0  2 32  0  3  7  6  0]
 [ 3  8  1  2  2 41  1  0  1  2]
 [ 4  0  3  5  3  2 12  4  3  2]
 [ 0  2  5  2  6  0  0 27  5  3]
 [ 2  0  4  7  2  1  4  1 35  3]
 [ 0  1 11  6  0  2  3  2  1 17]]
============== Iteration  3155
Loss:  1.28339636326 , Acc:  0.568359375
[[21  0  0  4  1  4  0  1  1  2]
 [ 1 49  1  0  0  4  0  0  1  0]
 [ 3  1 39  9  1  3  1  0  3  1]
 [ 4  2  4 24  0  1  2  3  8  4]
 [ 0  0  1  5 34  1  2  8  1  2]
 [ 1  3  2  1  0 28  1  0  3  1]
 [ 3  0  7 11  2  4 14  9  1  3]
 [ 3  2  3  5  3  1  5 20  1  2]
 [ 1  1  1  8  2  1  2  2 43  1]
 [ 6  2  6  5  0  4  9  3  0 19]]
============== Iteration  3160
Loss:  1.29114603996 , Acc:  0.564453125
[[20  0  0  3  3  5  3  3  2  1]
 [ 1 52  0  0  0  7  0  0  1  3]
 [ 0  0 19  3  1  6  4  2  4  1]
 [ 0  1  3 19  3  1  3 

============== Iteration  3255
Loss:  1.17333650589 , Acc:  0.599609375
[[18  0  3  3  1  4  3  1  1  3]
 [ 1 40  2  0  0  4  0  0  0  1]
 [ 1  1 39  5  1  2  0  3  0  2]
 [ 0  0  4 22  4  0  5  0  3  1]
 [ 0  0  1  9 40  1  3  2  2  2]
 [ 2  5  6  0  0 36  1  1  1  3]
 [ 1  0  2 12  2  3 16  3  4  8]
 [ 1  2  1  6  5  2  2 40  2  3]
 [ 3  1  0  5  5  0  1  3 28  1]
 [ 1  0  7  7  1  6  4  0  3 28]]
============== Iteration  3260
Loss:  1.23619115353 , Acc:  0.54296875
[[18  0  6  7  1  8  4  4  4  2]
 [ 1 51  1  0  0  2  0  0  1  1]
 [ 2  0 20  6  1  5  1  2  4  4]
 [ 1  0  3 21  1  1  9  6  7  7]
 [ 1  0  2  4 34  0  0 10  2  4]
 [ 1  2  4  0  1 34  0  1  1  4]
 [ 0  0  3  6  7  6 25  3  3  5]
 [ 0  0  3  3  4  0  3 30  6  3]
 [ 1  2  0  8  2  0  2  0 25  0]
 [ 3  0  6  4  1  1  7  1  2 20]]
============== Iteration  3265
Loss:  1.20834815502 , Acc:  0.560546875
[[25  0  4  2  1  6  1  5  2  3]
 [ 0 54  2  0  0  3  0  0  0  0]
 [ 1  0 28  6  1  7  2  1  2  8]
 [ 1  0  7 16  6  3  2  

============== Iteration  3360
Loss:  1.28964805603 , Acc:  0.521484375
[[27  0  7  1  2  4  2  3  2  7]
 [ 3 42  1  0  0  5  0  0  0  1]
 [ 5  1 24  7  0  8  1  2  4  4]
 [ 4  1  4 15  6  1  3  3  6  6]
 [ 0  0  2  7 32  1  0  6  2  2]
 [ 3  5  2  0  1 38  2  0  1  4]
 [ 7  0  4  9  4  1 17  9  2  6]
 [ 2  0  1  3  2  1  2 22  2  2]
 [ 1  0  1  4  8  2  6  3 30  5]
 [ 1  0  4  1  0  3  3  2  2 20]]
============== Iteration  3365
Loss:  1.15543007851 , Acc:  0.58984375
[[22  0  6  1  1  1  5  5  2  2]
 [ 1 40  1  0  0  2  0  0  0  0]
 [ 6  2 37 10  0  5  1  1  0  2]
 [ 2  0  5 25  3  0  0  3  5  3]
 [ 0  0  1  9 35  0  0  7  4  0]
 [ 2  4  3  2  1 39  0  1  0  0]
 [ 3  0  2  9  4  2 20  5  4  4]
 [ 2  0  5  2  2  1  1 35  2  5]
 [ 2  0  3  7  3  1  0  0 23  1]
 [ 5  2  9  3  0  6  1  2  3 26]]
============== Iteration  3370
Loss:  1.31412112713 , Acc:  0.533203125
[[25  0  5  3  0  3 10  7  2  2]
 [ 0 42  0  1  0  6  1  0  0  0]
 [ 3  0 19  3  3  4  3  4  3  3]
 [ 2  0  4 18  2  1  6  

============== Iteration  3465
Loss:  1.2792314291 , Acc:  0.537109375
[[24  1 11  5  1  4  1  3  0  2]
 [ 0 38  0  0  0  9  0  0  0  4]
 [ 1  0 30  1  0  1  1  1  3  5]
 [ 2  0  2 24  2  0  4  3  8  5]
 [ 0  0  3  7 35  1  2  9  1  2]
 [ 5  6  8  1  0 34  0  0  1  5]
 [ 4  0  4  5  3  2 20  5  3 11]
 [ 2  1  2  1  7  1  3 27  0  2]
 [ 1  0  1 10  4  2  2  2 21  1]
 [ 5  1 10  4  0  1  3  2  1 22]]
============== Iteration  3470
Loss:  1.27214980125 , Acc:  0.546875
[[22  1  8  4  0  3  7  4  3  3]
 [ 0 33  0  1  0  6  0  0  0  0]
 [ 1  1 25  7  2  4  2  1  1  4]
 [ 0  0  3 29  2  1  3  3  8  3]
 [ 0  0  2  4 39  2  1  7  2  1]
 [ 5  9  4  2  0 34  1  2  1  2]
 [ 0  0  6  7  4  3 17  5  3  7]
 [ 0  0  5  4  5  0  2 29  1  6]
 [ 0  0  0  5  3  2  5  0 30  0]
 [ 0  0  7  7  0  4  7  0  3 22]]
============== Iteration  3475
Loss:  1.23783278465 , Acc:  0.578125
[[30  0  5  4  0  2  4  4  1  2]
 [ 1 51  0  0  0  1  0  0  1  3]
 [ 6  3 17  4  4  5  1  1  2  8]
 [ 0  0  3 17  1  1  3  7  9  

============== Iteration  3570
Loss:  1.28941738605 , Acc:  0.53515625
[[21  0 10  8  0  1  3  6  1  4]
 [ 0 47  1  0  0  3  0  0  0  2]
 [ 2  0 22  6  3  5  0  1  0  8]
 [ 0  0  6 29  4  0  1  2  6  4]
 [ 0  1  1  7 33  1  4  4  6  0]
 [ 1  7  8  2  1 31  2  1  1  3]
 [ 5  0  4  6  5  5 16  6  0  3]
 [ 0  1  5  1  2  1  3 34  4  3]
 [ 1  2  0  4  7  0  4  2 19  1]
 [ 2  0  8  6  0  1  5  4  0 22]]
============== Iteration  3575
Loss:  1.20110499859 , Acc:  0.552734375
[[21  1  1  6  0  8  2  2  2  4]
 [ 0 50  1  0  0  4  0  0  0  1]
 [ 4  0 26  2  0  4  2  2  0  7]
 [ 1  0  5 20  0  2  3  0  5  3]
 [ 1  0  5  2 25  1  1  6  0  3]
 [ 3  5  1  1  1 47  1  0  0  4]
 [ 2  1  3 16  1  4 17  8  1 14]
 [ 1  1  2  5  4  1  0 26  3  3]
 [ 1  1  2  5  4  0  2  3 31  2]
 [ 4  1  7 11  1  5  2  0  1 20]]
============== Iteration  3580
Loss:  1.24712502956 , Acc:  0.54296875
[[24  1  5  3  1  1  5  2  2  4]
 [ 1 46  0  0  0  7  0  0  0  0]
 [ 3  2 23  5  2  5  1  4  0  7]
 [ 3  1  8 17  6  1  7  6

============== Iteration  3675
Loss:  1.17392790318 , Acc:  0.578125
[[26  0  4  7  1  3  5  1  0  2]
 [ 0 33  0  0  0  6  0  0  0  0]
 [ 2  1 28  3  0  7  3  4  0  4]
 [ 0  1  3 32  2  0  3  5  8  4]
 [ 0  0  0  4 36  0  2  8  5  1]
 [ 2  5  2  1  0 38  0  0  0  5]
 [ 3  0  3  6  3  0 18  7  3  7]
 [ 2  0  3  2  4  0  3 34  0  4]
 [ 2  0  0  9  7  1  3  3 29  5]
 [ 2  0  6  8  1  3  2  0  0 22]]
============== Iteration  3680
Loss:  1.20400631428 , Acc:  0.583984375
[[24  0  5  3  1  2  3  2  0  6]
 [ 1 43  0  0  0  8  1  0  0  1]
 [ 5  1 35  3  0  4  1  2  2  4]
 [ 2  1  7 18  3  2  3  4  5  5]
 [ 1  1  0  1 37  0  2  1  5  1]
 [ 2  5  4  2  0 41  1  1  1  1]
 [ 1  0  3  5  1  3 18  6  5  6]
 [ 1  1  4  4 10  1  3 31  2  2]
 [ 1  0  0  8  2  0  0  1 25  2]
 [ 0  1  4  8  0  1  5  2  4 27]]
============== Iteration  3685
Loss:  1.17929816246 , Acc:  0.578125
[[32  0  5  4  2  2  3  1  2  3]
 [ 0 50  0  0  0  3  1  0  0  1]
 [ 5  1 30 10  2  3  0  0  3  2]
 [ 1  1  5 18  2  1  4  5  7 

============== Iteration  3780
Loss:  1.11402451992 , Acc:  0.60546875
[[19  0  3  3  1  2  6  2  0  3]
 [ 0 74  1  0  0  1  0  0  0  1]
 [ 3  0 22  3  1  3  4  1  0  7]
 [ 0  0  1 20  3  0  7  2  1  2]
 [ 1  0  1  2 31  1  2  6  3  0]
 [ 1  7  5  3  0 36  0  0  2  1]
 [ 1  0  0  6  6  3 25 11  2  7]
 [ 1  0  0  5  2  0  5 36  2  2]
 [ 0  2  2  7  4  1  2  4 27  0]
 [ 1  1 11  8  2  7  0  1  0 20]]
============== Iteration  3785
Loss:  1.34948170185 , Acc:  0.515625
[[22  0  3  6  2  2  9  2  1  2]
 [ 2 37  1  0  0  6  0  0  1  0]
 [ 6  2 19 11  1  4  3  1  3  8]
 [ 0  0  1 23  3  0  3  2 17  3]
 [ 0  0  0  9 37  2  4  4  2  1]
 [ 3  2  2  1  0 28  2  1  2  1]
 [ 2  1  1  7  1  4 27  1  0  5]
 [ 1  0  4 10  6  0  5 25  5  5]
 [ 0  2  2  7  1  0  3  1 28  3]
 [ 5  1  7  6  2  2  4  0  3 18]]
============== Iteration  3790
Loss:  1.20778167248 , Acc:  0.564453125
[[28  1  2  3  1  1  3  6  1  2]
 [ 0 48  0  0  0  3  1  0  0  2]
 [ 4  3 29  3  1  3  0  4  2  9]
 [ 5  0  6 20  4  0  2  5  

============== Iteration  3885
Loss:  1.19374895096 , Acc:  0.5703125
[[29  0  5  6  0  3  1  3  1  3]
 [ 1 42  0  0  0  6  0  0  0  1]
 [ 4  0 28  4  2  3  1  3  3  6]
 [ 5  1  4 24  1  1  4  1  7  3]
 [ 0  1  0  6 33  0  4  3  5  1]
 [ 3  2  3  1  0 38  0  0  1  3]
 [ 2  0  2  9  6  3 22 10  2  6]
 [ 2  1  1  5  5  1  5 23  3  3]
 [ 0  1  0 11  2  1  2  1 30  0]
 [ 2  1  5  1  1  7  3  0  0 23]]
============== Iteration  3890
Loss:  1.26391327381 , Acc:  0.541015625
[[22  0  5  8  2  9  3  4  1  1]
 [ 0 44  0  0  0  7  0  0  0  1]
 [ 2  2 28  4  0  3  1  4  3  2]
 [ 1  0  5 21  4  2  2  3  2  5]
 [ 2  1  1  4 47  2  2  2  4  1]
 [ 1  5  3  1  1 36  2  1  1  1]
 [ 2  1  4  9  2  3 24  8  2  2]
 [ 0  2  4  8 10  0  2 18  2  1]
 [ 1  0  0  9  4  0  4  2 27  1]
 [ 1  1 16  3  0  1  5  4  0 10]]
============== Iteration  3895
Loss:  1.24114131927 , Acc:  0.564453125
[[27  2  8  7  0  3  4  5  0  4]
 [ 0 38  2  0  0  7  0  0  1  3]
 [ 0  1 25  4  0  2  2  0  1  3]
 [ 1  1  2 21  8  1  5  3

============== Iteration  3990
Loss:  1.190102458 , Acc:  0.568359375
[[22  0  5  5  1  7  5  4  1  3]
 [ 0 41  0  0  0  5  1  0  0  1]
 [ 7  0 26  3  0  4  3  4  2  5]
 [ 3  1  1 22  3  1  1  3  7  7]
 [ 0  1  1  3 36  2  1  4  2  1]
 [ 3  2  5  1  0 34  1  0  1  5]
 [ 6  0  1  3  2  2 23  9  2  6]
 [ 1  0  2  2  5  2  5 33  3  1]
 [ 0  0  0 12  3  2  1  0 31  1]
 [ 2  2  5  5  0  3  3  1  3 23]]
============== Iteration  3995
Loss:  1.25173997879 , Acc:  0.54296875
[[17  0  1  4  3  3  3  2  0  2]
 [ 0 38  0  0  0  8  2  0  0  2]
 [ 2  0 28  1  1  7  1  1  4  4]
 [ 1  1  4 35  3  0  5  3 10  3]
 [ 0  2  1  3 27  0  0  2  3  1]
 [ 6  4  5  2  0 26  1  0  0  2]
 [ 1  0  3 11  6  2 19  6  4  4]
 [ 1  0 10  3  9  2  2 22  0  0]
 [ 0  0  2  9  5  1  0  3 37  2]
 [ 1  2 18  3  1  1  5  0  4 29]]
============== Iteration  4000
Loss:  1.1345937252 , Acc:  0.595703125
[[23  1  7  0  2  4  2  5  2  3]
 [ 0 44  0  0  0  8  0  0  1  0]
 [ 2  1 32  6  0  1  1  0  1  2]
 [ 3  0  4 32  2  1  6  0  

============== Iteration  4095
Loss:  1.1898355484 , Acc:  0.58203125
[[24  0  4  5  1  3  5  3  1  4]
 [ 0 41  1  0  0  3  0  0  1  0]
 [ 2  0 29  4  1  6  0  2  1  2]
 [ 2  0  4 20  3  1  6  1  6  3]
 [ 0  0  1  3 34  0  4  8  2  0]
 [ 1  5  5  2  0 31  0  0  2  2]
 [ 3  0  6  6  4  4 32  7  3  4]
 [ 0  0  3  4  3  0  6 32  2  2]
 [ 0  0  3  6  3  0  0  3 34  1]
 [ 2  1  8  9  0  5  2  1  3 21]]
============== Iteration  4100
Loss:  1.27676749229 , Acc:  0.541015625
[[25  1  6  5  0  3  6  2  2  4]
 [ 0 30  0  0  0  4  0  0  0  0]
 [ 5  1 27  8  2  1  3  0  4  6]
 [ 0  2 13 22  5  0  3  5 17  4]
 [ 1  0  2  4 34  2  4  6  0  3]
 [ 2  8  5  0  0 32  1  1  0  1]
 [ 4  1  4  4  4  2 19  3  2  3]
 [ 1  1  1  2  6  0  3 33  2  1]
 [ 0  3  0  6  2  0  0  1 35  0]
 [ 2  0  8  3  0  2  6  2  4 20]]
============== Iteration  4105
Loss:  1.24882149696 , Acc:  0.53125
[[21  1  3  5  1  1  4  4  2  2]
 [ 1 38  1  0  0  6  0  0  0  0]
 [ 2  0 20  2  1  5  2  3  5  2]
 [ 4  0  3 29  5  2  5  5 10 

============== Iteration  4200
Loss:  1.20888543129 , Acc:  0.560546875
[[27  1  2  5  3  5  6  5  2  3]
 [ 0 46  2  0  0  3  0  0  0  1]
 [ 1  0 29  5  1  3  1  0  2  3]
 [ 1  0  3 25  5  1  2  3  5  6]
 [ 0  0  1  5 31  1  2  5  3  0]
 [ 0  8  1  2  0 33  2  1  1  2]
 [ 5  0  1  6  5  2 15  9  3  6]
 [ 0  1  3  4  7  1  4 30  2  2]
 [ 0  0  0  8  3  1  2  3 31  2]
 [ 3  1  7 10  1  2  4  1  2 20]]
============== Iteration  4205
Loss:  1.18824088573 , Acc:  0.5546875
[[27  1  8  9  2  2  2  2  1  1]
 [ 0 40  0  0  0  6  0  0  1  0]
 [ 4  1 27  5  0  7  4  2  1  1]
 [ 2  0  3 30  1  2  4  2  9  7]
 [ 0  0  0  1 36  1  7  7  6  0]
 [ 4  9  3  0  2 32  0  0  0  3]
 [ 2  0  5  6  3  1 18  4  5  5]
 [ 2  3  1  2  4  0  4 15  3  2]
 [ 1  0  0  9  0  3  1  1 39  2]
 [ 2  0  6  6  0  5  7  0  0 20]]
============== Iteration  4210
Loss:  1.19665575027 , Acc:  0.56640625
[[28  0  5  4  1  2  3  2  1  2]
 [ 1 42  0  0  0  2  1  0  0  1]
 [ 3  1 23  5  0  7  1  2  0  6]
 [ 1  0  4 33  2  2  2  4 

============== Iteration  4305
Loss:  1.22183358669 , Acc:  0.544921875
[[22  0  5  3  0  3  8  0  1  4]
 [ 0 33  1  0  0  4  0  0  0  2]
 [ 5  0 31 11  2  3  2  2  2  2]
 [ 4  0  7 18  4  2  9  2  4  1]
 [ 0  0  0  2 47  3  1  5  1  0]
 [ 2  2  5  0  0 31  2  2  0  4]
 [ 3  0  4  9  1  5 20  6  4  8]
 [ 1  1  3  6  8  0 10 23  1  1]
 [ 0  2  1  7  0  2  0  0 30  5]
 [ 2  1  6  2  2  3  6  1  0 24]]
============== Iteration  4310
Loss:  1.16852807999 , Acc:  0.5703125
[[26  1  7  7  0  2  4  5  1  1]
 [ 1 38  0  0  0  7  0  0  0  0]
 [ 1  0 26  4  1  9  3  6  0  3]
 [ 1  0  2 26  2  0  5  6  8  3]
 [ 0  1  0  2 38  2  2  3  1  1]
 [ 0  3  2  1  0 32  1  0  1  5]
 [ 2  0  4  6  5  2 19  2  2  4]
 [ 1  1  2  5  8  0  3 32  4  1]
 [ 1  1  1 11  3  0  0  2 32  3]
 [ 1  3 12  3  1  3  7  1  0 23]]
============== Iteration  4315
Loss:  1.22661590576 , Acc:  0.556640625
[[24  2  4  4  0  2  4  4  1  2]
 [ 1 41  0  1  0 11  0  0  0  2]
 [ 7  1 28  4  1  8  1  0  3  6]
 [ 0  0  4 21  2  2  5  3

============== Iteration  4410
Loss:  1.1561794281 , Acc:  0.595703125
[[21  3  3  5  0  3  4  6  1  3]
 [ 0 38  0  0  0  3  0  0  0  1]
 [ 3  1 25  2  0  3  0  1  0  4]
 [ 3  1  3 30  3  2  7  3  4  4]
 [ 2  1  0  1 36  0  1  3  3  0]
 [ 4  5  3  1  2 38  0  0  1  2]
 [ 0  0  1  9  0  6 28  8  5  9]
 [ 0  0  1  1  4  0  6 33  1  0]
 [ 1  1  3  7  1  3  0  1 29  1]
 [ 2  2 10  5  1  6  6  1  0 27]]
============== Iteration  4415
Loss:  1.17473375797 , Acc:  0.58984375
[[26  2  7  2  0  1  4  2  3  3]
 [ 0 46  0  0  0  7  0  0  0  1]
 [ 0  2 24  1  0  4  0  1  0  4]
 [ 4  1  4 24  3  0  1  4 11  5]
 [ 0  0  0  7 32  2  5  8  5  2]
 [ 2  3  3  0  1 42  1  1  0  5]
 [ 1  0  1  5  2  6 28  5  2  8]
 [ 1  1  2  4  2  1  2 24  2  1]
 [ 0  0  1  7  4  1  3  0 38  3]
 [ 1  3  5  4  2  1  4  1  2 18]]
============== Iteration  4420
Loss:  1.12709736824 , Acc:  0.599609375
[[24  0  1  8  2  7  3  2  3  2]
 [ 0 47  0  0  0  3  0  0  1  0]
 [ 2  1 35  5  2  5  0  3  3  3]
 [ 2  1  1 31  3  0  3  1

============== Iteration  4515
Loss:  1.18850409985 , Acc:  0.568359375
[[25  0  8  5  2  7  3  1  0  2]
 [ 0 38  0  0  0  6  0  0  0  1]
 [ 1  2 26  4  0  7  1  3  1  4]
 [ 2  1  8 21  1  1  2  2  8  9]
 [ 0  2  4  2 34  0  0  2  3  0]
 [ 0  4  3  1  0 31  1  0  2  0]
 [ 2  0  2  6  5  1 18 10  2  6]
 [ 2  0  4  6  4  0  3 39  2  2]
 [ 0  1  2  7  2  0  1  4 37  2]
 [ 1  0 10  6  0  6  3  0  3 22]]
============== Iteration  4520
Loss:  1.12336528301 , Acc:  0.59375
[[25  0  9  4  0  4  5  4  0  0]
 [ 0 44  0  0  0 10  0  0  1  0]
 [ 3  3 27  7  1  3  3  2  2  5]
 [ 4  0  1 21  4  2  6  1  5  3]
 [ 2  1  1  2 39  2  3  8  3  0]
 [ 2  6  2  2  0 42  1  0  1  0]
 [ 3  1  4  6  3  3 31  3  4  8]
 [ 1  0  1  4  2  0  3 23  1  1]
 [ 1  0  3  5  0  1  0  0 34  0]
 [ 3  0  9  2  1  0  5  0  2 18]]
============== Iteration  4525
Loss:  1.11958491802 , Acc:  0.583984375
[[21  0  2  3  2  5  4  8  4  2]
 [ 0 39  0  0  0  4  0  0  0  2]
 [ 2  1 31  2  2  7  1  0  4  7]
 [ 2  1  2 22  6  0  4  4  

============== Iteration  4620
Loss:  1.19381797314 , Acc:  0.56640625
[[25  2  5  2  2  5  3  2  7  2]
 [ 0 47  0  0  0  4  0  0  0  0]
 [ 3  0 26  4  2  3  4  2  1  3]
 [ 6  1  4 23  4  3  3  0  7  6]
 [ 0  1  1  4 31  0  2  4  2  1]
 [ 2  7  2  1  0 28  1  0  0  4]
 [ 2  1  4  6  6  3 20  2  3  8]
 [ 1  1  3  4  4  1  5 28  4  2]
 [ 1  1  1  3  2  1  2  1 28  1]
 [ 4  0 11  2  1  2  1  0  6 34]]
============== Iteration  4625
Loss:  1.16968715191 , Acc:  0.587890625
[[23  0  3  0  1  2  5  2  0  4]
 [ 1 51  0  0  0  8  1  0  0  1]
 [ 5  0 24  6  1  7  1  1  4  7]
 [ 3  1  3 23  2  0  2  2  6  2]
 [ 0  1  2  2 29  0  3  5  3  0]
 [ 4  5  5  1  0 28  1  2  1  1]
 [ 2  0  2  8  1  6 24  5  6  5]
 [ 2  0  6  3  1  0  3 34  0  0]
 [ 1  1  4  9  2  1  1  3 42  4]
 [ 2  0  3  2  2  4  1  3  1 23]]
============== Iteration  4630
Loss:  1.20714640617 , Acc:  0.568359375
[[27  0  6  7  3  5  4  3  1  0]
 [ 0 40  0  0  0  3  0  0  0  2]
 [ 2  0 25  6  1  8  1  1  1  5]
 [ 2  0  6 26  2  0  5  

============== Iteration  4725
Loss:  1.23667895794 , Acc:  0.544921875
[[27  1  3  7  0  3  5  4  4  3]
 [ 0 44  0  0  0  1  0  0  0  2]
 [ 2  3 18  5  2  5  1  1  1  6]
 [ 4  1  2 21  4  3  1  1  4  6]
 [ 0  1  0  3 43  0  2  5  3  0]
 [ 1  5  1  0  1 33  1  0  1  6]
 [ 1  0  2  1  2  4 13  4  6 12]
 [ 2  0  3  5  6  0  4 33  1  5]
 [ 2  0  1  9  2  2  3  1 30  3]
 [ 3  2 10  7  0  2  6  4  3 17]]
============== Iteration  4730
Loss:  1.2153660059 , Acc:  0.576171875
[[36  0  0  5  2  2  4  3  1  3]
 [ 1 37  0  0  0  6  0  0  0  2]
 [ 6  1 28  7  2  4  2  2  2  2]
 [ 5  0  1 24  1  3  8  2  8  5]
 [ 0  0  0  5 33  1  2  2  5  1]
 [ 2  4  0  0  0 36  1  1  2  1]
 [ 3  0  1  6  2  2 13  5  4  7]
 [ 0  1  2  4  5  0  2 31  0  5]
 [ 1  1  1  6  5  1  1  0 34  1]
 [ 4  1 11  6  0  0  6  2  4 23]]
============== Iteration  4735
Loss:  1.12924706936 , Acc:  0.60546875
[[27  0  7  6  1  0  3  0  1  2]
 [ 1 43  0  0  0 10  0  0  0  1]
 [ 3  1 28  2  0  4  0  0  0  3]
 [ 3  1  6 22  2  0  3  4

============== Iteration  4830
Loss:  1.18252170086 , Acc:  0.5859375
[[28  0  2  0  2  3  4  2  4  0]
 [ 2 45  0  0  0  6  0  0  1  1]
 [ 2  0 20  4  1  3  0  2  1  5]
 [ 3  0  4 23  3  0  6  2  9  2]
 [ 0  1  4  3 33  1  2  4  4  1]
 [ 2  3  1  2  0 42  2  0  2  0]
 [ 4  0  2  7  5  4 21  8  4  4]
 [ 3  1  3  1  5  0  2 40  3  1]
 [ 2  1  1  4  3  2  1  3 26  3]
 [ 3  1  7  7  2  3  3  0  3 22]]
============== Iteration  4835
Loss:  1.07694983482 , Acc:  0.640625
[[25  1  2  4  1  5  3  3  1  1]
 [ 0 56  1  0  0  5  0  0  0  0]
 [ 2  0 29  7  0  3  0  1  3  6]
 [ 2  0  4 26  1  1  5  3  7  4]
 [ 0  1  2  6 29  1  3  3  2  0]
 [ 3  5  0  1  0 35  1  0  0  1]
 [ 2  0  1  4  0  2 27  4  4  7]
 [ 0  0  7  2  2  0  3 33  2  1]
 [ 1  0  1  5  0  1  3  3 31  2]
 [ 1  0  4  8  0  5  4  0  0 37]]
============== Iteration  4840
Loss:  1.11870753765 , Acc:  0.591796875
[[24  0  4  3  0  4  6  5  2  1]
 [ 0 46  1  0  0  2  0  0  1  0]
 [ 4  0 30  3  0  6  1  3  2 11]
 [ 1  1  3 18  1  1  7  4  7

============== Iteration  4935
Loss:  1.16715276241 , Acc:  0.5625
[[36  1  3  8  1  2  2  5  0  0]
 [ 1 49  3  0  0  9  0  0  0  1]
 [ 5  2 32  5  1  4  1  3  0  6]
 [ 2  0  4 22  3  1  5  4  8  2]
 [ 0  0  0  2 26  1  2  4  2  2]
 [ 1  1  2  0  1 27  0  0  0  3]
 [ 3  0  4  6  6  1 20  6  1 10]
 [ 1  0  2  4  3  1  8 28  2  1]
 [ 1  0  2  8  3  3  3  2 30  4]
 [ 1  2  5  3  1  5  6  1  2 18]]
============== Iteration  4940
Loss:  1.15560173988 , Acc:  0.578125
[[26  1  8  3  0  3  4  7  2  2]
 [ 0 45  1  0  0  2  0  0  0  1]
 [ 2  0 33  1  2  3  4  3  0  5]
 [ 1  1  6 30  4  1  3  5  7  3]
 [ 0  0  0  2 28  1  4  2  4  2]
 [ 2  3  8  1  0 27  1  2  1  1]
 [ 1  0  8  5  3  1 21  4  3  5]
 [ 0  2  6  4  4  0  0 31  2  0]
 [ 0  0  4  2  3  3  0  1 30  1]
 [ 3  0 12  7  0  1  7  4  1 25]]
============== Iteration  4945
Loss:  1.17577064037 , Acc:  0.5859375
[[28  0  2  4  1  4  6  3  0  1]
 [ 0 55  1  0  0  6  0  0  1  0]
 [ 7  1 32  7  2  3  1  3  1  7]
 [ 1  0  4 26  3  1  2  3  4  2]
